In [4]:
import tensorflow as tf
from tensorflow import keras 
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten 

#Dropout Regularization: To get rid off over fitting problem 
from keras.layers import Conv2D, MaxPool2D
from keras import backend as k

In [5]:
fashion_mnist.load_data()

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 42s 2us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 4us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 7s 2us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [6]:
#Number of the class - do not change unless the data change 
num_classes = 10

In [7]:
#Size of the batch and epoch of the data
batch_size = 64
epochs = 24 


In [8]:
#input image dimention
img_rows, img_cols = 28, 28


In [9]:
#the data shufffled and split between train and test sets 
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

In [10]:
x_train.shape

(60000, 28, 28)

In [11]:
x_test.shape

(10000, 28, 28)

In [12]:
len(y_train)

60000

In [13]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [14]:
x_train.shape[0]

60000

In [17]:
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

In [18]:
input_shape

(28, 28, 1)

In [19]:
x_train.shape

(60000, 28, 28, 1)

In [20]:
#Type convert and scale the training and test data
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /=255.
x_test /=255.

print('X_train Shape:', x_train.shape)
print('X_test Shape:', x_test.shape)
print(y_train[0:3])

X_train Shape: (60000, 28, 28, 1)
X_test Shape: (10000, 28, 28, 1)
[9 0 0]


In [21]:
#Convert class vector to binary class metrics. One hot encoding 
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)
print(y_train[0:2])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


CNN CODE

In [22]:
#Define the model 
model = Sequential()


In [23]:
num_classes

10

In [24]:
#Create a CNN to classify the image 
model.add(Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=input_shape))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(32, kernel_size=(3,3), activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

C:\Users\moham\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [26]:
#define compile to minimize categorical loss, use some optimize to optimize , and optimize to maximum accurecy 
model.compile(loss=keras.losses.categorical_crossentropy, 
              optimizer=keras.optimizers.Adam(), 
              metrics=['accuracy'])
#Train the model and test/validate the model with the test data after each cycle (epoch) through th etraining data
#Return history of loss and accuracy foe each epoch 

hist = model.fit(x_train, y_train, 
                 batch_size = 64, 
                 epochs = 24,
                 verbose = 1,
                 validation_data=(x_test, y_test))

Epoch 1/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 29s 25ms/step - accuracy: 0.8477 - loss: 0.4302 - val_accuracy: 0.8672 - val_loss: 0.3613
Epoch 2/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 22s 24ms/step - accuracy: 0.8728 - loss: 0.3591 - val_accuracy: 0.8852 - val_loss: 0.3150
Epoch 3/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 22s 23ms/step - accuracy: 0.8874 - loss: 0.3200 - val_accuracy: 0.8930 - val_loss: 0.2969
Epoch 4/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 32s 34ms/step - accuracy: 0.8971 - loss: 0.2929 - val_accuracy: 0.8962 - val_loss: 0.2914
Epoch 5/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 30s 32ms/step - accuracy: 0.9040 - loss: 0.2693 - val_accuracy: 0.9020 - val_loss: 0.2728
Epoch 6/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 27s 29ms/step - accuracy: 0.9117 - loss: 0.2475 - val_accuracy: 0.9037 - val_loss: 0.2707
Epoch 7/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 41s 29ms/step - accuracy: 0.9176 - loss: 0.2335 - val_accuracy: 0.9053 - val_loss: 0.2782
Epoch 8/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 23s 24ms/step - accuracy: 0.9216 - loss: 0.2192 - 

In [27]:
hist.history


{'accuracy': [0.847683310508728,
  0.8728166818618774,
  0.8873999714851379,
  0.8970500230789185,
  0.904033362865448,
  0.911716639995575,
  0.9176499843597412,
  0.9215666651725769,
  0.9262833595275879,
  0.9310166835784912,
  0.935283362865448,
  0.9379666447639465,
  0.9398333430290222,
  0.9429333209991455,
  0.9461333155632019,
  0.9474499821662903,
  0.951616644859314,
  0.9538333415985107,
  0.9557833075523376,
  0.9574999809265137,
  0.9590833187103271,
  0.9585833549499512,
  0.9646000266075134,
  0.9640499949455261],
 'loss': [0.4301601052284241,
  0.3591361343860626,
  0.3200465440750122,
  0.2929098606109619,
  0.2692822515964508,
  0.24754184484481812,
  0.23350727558135986,
  0.21920426189899445,
  0.20543698966503143,
  0.19380870461463928,
  0.1806887686252594,
  0.17174944281578064,
  0.16589374840259552,
  0.15457206964492798,
  0.14659324288368225,
  0.1441473513841629,
  0.13156265020370483,
  0.12552344799041748,
  0.11962855607271194,
  0.11211394518613815,
  0

In [28]:
#Model Summery 
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 11, 11, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 5, 5, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 800)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       102,528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 363,008 (1.38 MB)

 Trainable params: 121,002 (472.66 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 242,006 (945.34 KB)